### ISSUE TITLE
Isn't working on my Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by pandeytapan** [justjanne/powerline-go#231]
Giving me error  go/src/github.com/justjanne/powerline-go/segment-rbenv.go:56:16: undefined: os.UserHomeDir on running command go get -u github.com/justjanne/powerline-go. I am using Ubuntu 18.04.5 LTS

**Comment by mattle** [comment]
I got the same error and I think this might be fixed in a later version of Go than what is installed by apt in Ubuntu 18.04.

Go 1.12 appears to include os.UserHomeDir: https://golang.org/pkg/os/#UserHomeDir
The version of Go installed by apt in Ubuntu 18.04 is currently 1.10.4

What does "go version" show for you?

**Comment by pandeytapan** [comment]
@mattle Thanks for your suggestion. Once I updated the go from 1.10 to 1.15 it is working fine for me and I am able to install powerline-go.
